# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - projects.md

footer: 2022

style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
